### ISSUE TITLE
Issue while exec the jmeter container 

### ISSUE THREAD

**Issue by sattishv** [Rbillon59/jmeter-docker-compose-starterkit#7]
Hi,

We are facing issues while running the container . We were able to build the image. But while running it we are prompted with this error.

exec /opt/entrypoint.sh: no such file or directory.

Even when i tried to build the jmeter image alone i got the same error. 
![Screenshot 2023-10-17 190919](https://github.com/Rbillon59/jmeter-docker-compose-starterkit/assets/7449241/bf3b4de9-11eb-400d-82ae-d72577e6cdc2)

Could you please review and let us know am i doing the right way.

thanks
Sattish

**Comment by Rbillon59** [comment]
Hello @sattishv 

This project is meant to be used with docker-compose. You can find the resources in the [README](https://github.com/Rbillon59/jmeter-docker-compose-starterkit/blob/master/README.md) file. The [runtime](https://github.com/Rbillon59/jmeter-docker-compose-starterkit#runtime) section should cover your needs.

To explain your error. You're trying to use the jmeter image in standalone but actually, the entrypoint.sh does not exist in the container, it's mounted from this repo. To be honest, I'am not even sure you can run my JMeter image in standalone, the error you're seeing is probably the first of many other, because really, this project is tailored to be used with docker compose.

**Comment by sattishv** [comment]
Thanks for your immediate response. Appreciate it

Initially i executed the project with docker-compose, since i got the same error pasted above . I tried to check the standalone version of it. With docker-compose all the containers started successfully except the jmeter instances
![Screenshot 2023-10-18 082653](https://github.com/Rbillon59/jmeter-docker-compose-starterkit/assets/7449241/f947f277-ad91-469f-be23-9627710a49a6)
To understand why the jmeter instances exited i checked the container logs . Got the same error pasted below
![Screenshot 2023-10-18 082709](https://github.com/Rbillon59/jmeter-docker-compose-starterkit/assets/7449241/900891aa-011d-4c96-a570-e7a4675bbe74)
Not sure whether I missed some configuration.
Thanks
sattish.

**Comment by Rbillon59** [comment]
Are you running the docker compose from the repo root ?

Because the entrypoint.sh needs to be mounted from the repo to the Jmeter containers. If you're using a custom path, you need To update the mount path of that file

**Comment by sattishv** [comment]
I am running the docker compose from the repo root. 

![New screenshot](https://github.com/Rbillon59/jmeter-docker-compose-starterkit/assets/7449241/c9c07624-dfad-4afe-b18f-af1830395c52)

Only difference here, is i am using Windows Subsytem for Linux WSL to invoke docker commands since our OS is windows

**Comment by sattishv** [comment]
Hi Sorry for the discommode i started again from the demo project. We were able to create and schedule the my-scenario.jmx script  with all the containers. Will modify and try to execute our testcases. Thanks

**Comment by Rbillon59** [comment]
Awesome ! thanks for letting me know.

Please let me know if everything is ok so I can close the issue

**Comment by sattishv** [comment]
We can close this issue.
